board:
  name: egokb_control
  vendor: egokb
  socs:
    - name: nrf52840
      variants:
        - name: zmk
  revision:
    format: major.minor.patch
    default: 1.0.0
    revisions:
      - name: 1.0.0
